# To re-generate this file, run:
#   nix run github:nix-community/dream2nix#detect-projects $source
# ... where `$source` points to the source of your project.

[eslint]
name = "eslint"
relPath = ""
subsystem = "nodejs"
translator = "package-json"
translators = [ "package-json",]

[eslint.subsystemInfo]
noDev = true
noedjs = 18
