[book]
authors = ["Robert Hensing", "Various module authors"]
language = "en"
multilingual = false
src = "src"
title = "flake-parts"

[output.html]
git-repository-url = "https://github.com/hercules-ci/flake-parts"
edit-url-template = "https://github.com/hercules-ci/flake.parts-website/edit/main/site/{path}"
additional-js = [ "no-edit-options.js" ]
additional-css = [ "flake-parts.css" ]
no-section-label = true

[output.html.print]
enable = false  # big single page; don't need that

[output.linkcheck]
follow-web-links = false # no Internet during the build
